# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build win x64
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o runnerGo_win_x64.exe runnerGo.go

    - name: Build win x32
      run: CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o runnerGo_win_x32.exe runnerGo.go

    - name: Build mac x64
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o runnerGo_mac_x64 runnerGo.go

    - name: Build mac m1
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm go build -o  runnerGo_mac_arm64 runnerGo.go

    - name: Build linux x64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o runnerGo_linux_x64 runnerGo.go

    - name: Build liunx arm64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o runnerGo_linux_arm64 runnerGo.go 

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          runnerGo_win_x64.exe
          runnerGo_win_x32.exe
          runnerGo_mac_x64
          runnerGo_mac_arm64
          runnerGo_linux_x64
          runnerGo_linux_arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

